### ISSUE TITLE
[WORK] 데이터 선정 2

### ISSUE THREAD

**Issue by JiEuNparrk** [Dementia-Diagnosis-Project/memoria_AI#11]
# WORK PLAN 
- [x] 영상 데이터셋 구축
- [x] tabular 데이터셋 (진단명, 나이, 성별 등) 구축
- [x] 영상 데이터 전처리

# ISSUES
### 문제상황
1. OASIS 대상자 수 부족
2. OASIS에서 tabular 데이터셋을 만드는데 필요한 정보 부족

### 예상 해결 방안 list 
- [x] 활용하는 데이터 베이스를 OASIS에서 ADNI로 변경

### (해결시) 해결방법   
1. ADNI 데이터 베이스에서 알츠하이머 치매 외에 인지기능에 영향을 끼칠 수 있는 다른 신경질환, 기분질환을 제외한 대상자 선정
2. 영상을 기준으로 선정한 명단에서 인구학적 및 임상정보 쿼리

# RESULTS
인구학적 및 임상정보가 모두 존재하는 대상자 => 정상: 1629, 치매: 1201명 (모델 학습 시키기에 충분함)
