### ISSUE TITLE
[WORK] Patch SVDD 모델 선정

### ISSUE THREAD

**Issue by Polar-Bear-Poby** [Dementia-Diagnosis-Project/memoria_AI#14]
# WORK PLAN 
- [x] 모델 : Patch SVDD
- [x] 사용 프레임워크 : pytorch
- [x] MRI image 중 NC (=Normal) class에 속한 image만으로 모델 학습
- [x] inference에서는 MRI 이미지와 anomaly map 이미지 출력
- [ ]  Tensorboard와 W&B 연결하여 모니터링

# ISSUES
### 문제상황
1. Colab에서 terminal 명령어로 py파일을 실행하면
colab pro +의 background 실행 기능 사용 불가
2. Inference 수행할 때 train image에서 feature를 추출하는 과정에서 많은 시간 소요
3. Colab으로 학습할 때 system 메모리가 증가하여, 제공된 용량을 초과하면 학습 중단
4. Server에서 shape이 안 맞는다는 이슈 (inspection.py 수정한 이후 발생...)
5. Valid, Test를 위한 Mask 요청

### 예상 해결 방안 list 
- [x] py파일을 ipynb 형식으로 수정한 다음 실행
- [x] 서비스 단계에서 사용할 feature들을 미리 저장하고,
inference 수행할 때 load 하는 방식으로 변경
- [x] GPT한테 물어보기....
- [ ] 서버에서 안 돌아가면 돌아갈 때까지 back!!
- [x] 지은님한테 부탁

### (해결시) 해결방법   
- [x] py파일을 ipynb 형식으로 변경하여 다음 실행
- [x] Inference 과정에서 npy형식으로 저장한 feature를 load함으로써
추론 시간을 줄이는데 성공
- [x] loss.item()을 활용, 사용하지 않은 변수 del ! (ing)
- [ ] back (ing)
- [x] 지은님께서 OASIS 데이터에서 mask 파일 생성해주심

# RESULTS
- 해당 작업 결과
Server 할당 받은 후 다양한 결과 수행 (ing)
# Experiments 1
|Epoch|lambda|# of patch |AUC(이상탐지)|AUC(픽셀 이상탐지)|
|:---:|:---:|:---:|:---:|:---:|
|15|1|100|0.705|0.882|

추후 Epoch 100이상 결과 첨부

# Experiments 2
|Epoch|lambda|# of patch |AUC(이상탐지)|AUC(픽셀 이상탐지)|
|:---:|:---:|:---:|:---:|:---:|
|15|1|150|0.691|0.893|

추후 Epoch 100이상 결과 첨부

# Experiments 3
|Epoch|lambda|# of patch |AUC(이상탐지)|AUC(픽셀 이상탐지)|
|:---:|:---:|:---:|:---:|:---:|
|15|0.1|150|0.736|0.847|

추후 Epoch 100이상 결과 첨부

# Experiments 4
Sharpening 이미지 데이터 세트 1 수행
|Epoch|lambda|# of patch |AUC(이상탐지)|AUC(픽셀 이상탐지)|
|:---:|:---:|:---:|:---:|:---:|
|TBD|TBD|TBD|TBD|TBD|

# Experiments 5
Sharpening 이미지 데이터 세트 2 수행
|Epoch|lambda|# of patch |AUC(이상탐지)|AUC(픽셀 이상탐지)|
|:---:|:---:|:---:|:---:|:---:|
|TBD|TBD|TBD|TBD|TBD|

**Comment by Polar-Bear-Poby** [comment]
### Visualize 속도 개선

Test 데이터의 anomaly map을 생성할 때 best model(=encoder)로 훈련 이미지에서 임베딩을 추출할 때
많은 시간 소요

### 해결방안

훈련 이미지로부터 추출한 임베딩 데이터를 load하는 방식으로 변경하여 test 데이터의 anomaly map 생성 시간 감소
