### ISSUE TITLE
[WORK] 영상 데이터 sharpening

### ISSUE THREAD

**Issue by JiEuNparrk** [Dementia-Diagnosis-Project/memoria_AI#16]
# WORK PLAN 
- [x] 모델 성능 향상

# ISSUES
### 문제상황
영상 데이터의 resolution이 좋지 않음

### (해결시) 해결방법
- [X] numpy와 nibabel을 활용하여 대상자의 각 영상 데이터의 array에 sharpening filter를 곱해줌   
- [X] filter_1=np.array([[-1,-1,-1], [-1,9,-1],[-1,-1,-1]])
- [X] filter_2=np.array([[0,-1,0],[-1,5,-1],[0,-1,0]])

# RESULTS
- 각 대상자마다 총 2개의 filter로 정도가 다른 sharpening 처리
